version: '3.8'

services:
  # MongoDB для основного бота (pure_bot)
  mongodb:
    image: mongo:6.0
    restart: unless-stopped
    expose:
      - "27017"
    volumes:
      - mongodb_data:/data/db

  # Основной бот (pure_bot)
  bot_pure:
    build:
      dockerfile: service.dockerfile
      context: .
    command: python -u bot.py
    restart: unless-stopped
    depends_on:
      - mongodb
    env_file:
      - .env
    volumes:
      - ./:/bot

  # Второй бот (wb)
  bot_wb:
    build:
      dockerfile: service.dockerfile
      context: .
    command: python -u bot1.py
    restart: unless-stopped    
    depends_on:
      - mongodb
    env_file:
      - .env
    volumes:
      - ./:/bot

  api:
    build:
      context: .
      dockerfile: service.dockerfile
    command: python -u web_admin.py
    restart: unless-stopped
    depends_on:
      - mongodb
    env_file:
      - .env
    ports:
      - "${API_PORT}:8000"
    volumes:
      - ./:/app

volumes:
  mongodb_data:
